### ISSUE TITLE
data_connection_checker

### ISSUE THREAD

**Issue by DarkHeros09** [RounakTadvi/internet_connection_checker#2]
what is the difference between this package and the data_connection_package?

**Comment by wltiii** [comment]
This package implements null-safety.

At the time this package was created, the developer of data_connection_checker - to what I assume you are referring - had not migrated that package to null-safety. There were at least two pull requests that did so and were languishing for quite some time. Indeed, the developer had not done anything with said package since 2019.

**Comment by DarkHeros09** [comment]
alright thank you for the clarification.
Now the real question is Will this package be maintainable, support other platforms and can i use it in a production app?
anyway I'll close this.

**Comment by RounakTadvi** [comment]
Surely, this package will be maintained @DarkHeros09

**Comment by DarkHeros09** [comment]
> Surely, this package will be maintained @DarkHeros09 

Great happy to hear that, thank you for your efforts.
