### ISSUE TITLE
Three requests at the same time

### ISSUE THREAD

**Issue by AhmedEzio47** [RounakTadvi/internet_connection_checker#29]
The current code makes three requests to 3 different addresses at the same time which is pretty data-consuming, isn't it better to wait for a request to finish, and if it's a failure, try the next?
![image](https://user-images.githubusercontent.com/17653367/189539321-7fb263d8-1cae-4512-9671-efbf2a1dd373.png)

`  Future<bool> get hasConnection async {
    final Completer<bool> result = Completer<bool>();
    int length = addresses.length;

    for (final AddressCheckOptions addressOptions in addresses) {
      // ignore: unawaited_futures
      isHostReachable(addressOptions).then(
        (AddressCheckResult request) {
          length -= 1;
          if (!result.isCompleted) {
            if (request.isSuccess) {
              result.complete(true);
            } else if (length == 0) {
              result.complete(false);
            }
          }
        },
      );
    }

    return result.future;
  }`

A small tweak to this function will do the trick.
Thank you.

**Comment by gampixi** [comment]
This package just attempts to establish a connection with the given servers, which should have very little overhead. How much data usage are you measuring?

**Comment by RounakTadvi** [comment]
@AhmedEzio47 Kindly use the latest version of the package it does not replies on Socket anymore, moreover when a request is made it just takes into account the statusCode received from the Url and not the response body so the overhead is not much. Since this issue has been inactive for a while, I’ll be closing it now. If the problem persists, please file a new issue.
