### ISSUE TITLE
Connection checker returning false even there is network connection.

### ISSUE THREAD

**Issue by Tomman85** [RounakTadvi/internet_connection_checker#30]
So there is the huge problem, when user have low network signal or when have some kind of slower network. 
Connection checker returning false but in real, user have the network. Any solution?

**Comment by Emmakade** [comment]
It work fine for me in debug mode but after i built Apk release, It bring false always even when the user have internet. 
Who will help? 

> Maybe you should try to increase `checkTimeout` in `createInstance`?

**Comment by Emmakade** [comment]
> Maybe you should try to increase `checkTimeout` in `createInstance`?

Good day sir/ma, the plugin work fine in debug mode but as soon as build release apk, it bring no internet always. please help @OlyaKovalchuk @MrCsabaToth @MrCsabaToth

**Comment by MrCsabaToth** [comment]
> 

This sounds to me a different problem than the original issue. The original issue i about a so called "lie fi", when the wifi and data connection is intermittent. However you say your issue is debug/release related, and always happens. So please open a separate issue. Questions: does the release version get internet permissions and is it tested in the same wifi? I'm asking the latter because one of my users had special proxy/network setup where the DNS servers we originally test were not accessible at all. Therefore in my app I had to make the internet connection test domains / IP addresses configurable (https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/issues/121). Same thing happened with me with IPv4 vs IPv6 IP addresses so one of my PRs introduced a mixture of them (so any of them can succeed https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/issues/190). I suggest you to debug what happens exactly.

**Comment by EmreKabali** [comment]
Hi,
Nowadays i face up similar problem at IOS and Android devices. Even if there is network connection, sometimes package return false.

Version : ^1.0.0+1

**Comment by Trupti-vaniya** [comment]
Hello,
I am experiencing a similar issue on both Android and iOS devices. Despite being connected to the internet, there are instances where the package returns a false result.
Version: ^1.0.0+1

**Comment by Tomman85** [comment]
I found a new library not too long ago. Since I've been using it I haven't noticed the old problems
You can try use this lib https://pub.dev/packages/connecteo

**Comment by RounakTadvi** [comment]
@Tomman85 Kindly try the latest version of the package, it does not relies on Socket anymore. Since this issue has been inactive for a while, I’ll be closing it now. If the problem persists, please file a new issue.
