### ISSUE TITLE
Question About Internet Connection Checker Behavior

### ISSUE THREAD

**Issue by ibrahimEltayfe** [RounakTadvi/internet_connection_checker#48]
Hi,

First of all, thank you for your work on this package, I appreciate your efforts.

I have a question about the behavior of the internet connection checker.
Currently, it seems that every endpoint listed in the addresses is triggered each time I check for an internet connection. Wouldn't it be more efficient to check one endpoint first and, if it succeeds, confirm there is an internet connection? If the first endpoint fails, the next one could be tried, continuing until all addresses are checked to ensure no connectivity. This approach might reduce unnecessary requests.

Additionally, out of curiosity, could you explain the reasoning behind the switch from Socket to http in the implementation?

Thank you again :)

**Comment by RounakTadvi** [comment]
Thank you for reaching out with your question!

The change from using Socket to the http package was primarily to support the web platform. The Socket implementation doesn't work on the web since browser environments restrict low-level network socket access for security reasons. 
Switching to the http package ensures that the library works consistently across all platforms, including web.

And to answer you query in which why every endpoint is triggered is for reliability, if the selected endpoint is temporarily down or inaccessible, it might falsely indicate no internet connectivity. Using multiple addresses ensures redundancy, reducing the chance of false negatives.

**Comment by ibrahimEltayfe** [comment]
> Thank you for reaching out with your question!
> 
> The change from using Socket to the http package was primarily to support the web platform. The Socket implementation doesn't work on the web since browser environments restrict low-level network socket access for security reasons. Switching to the http package ensures that the library works consistently across all platforms, including web.
> 
> And to answer you query in which why every endpoint is triggered is for reliability, if the selected endpoint is temporarily down or inaccessible, it might falsely indicate no internet connectivity. Using multiple addresses ensures redundancy, reducing the chance of false negatives.

Thank you

**Comment by RounakTadvi** [comment]
@ibrahimEltayfe You're welcome. Feel free to open a issue or you have any query in future I'm happy to help 😄.
