### ISSUE TITLE
hasConnection Mobile data error

### ISSUE THREAD

**Issue by miguelflores1993** [RounakTadvi/internet_connection_checker#6]
My phone does not have internet or megabytes of my mobile or telephone network, but nevertheless it returns me that I am connected, I think the **InternetConnectionChecker().hasConnection** method is failing.

**Comment by flutteresbolivia** [comment]
Please Help.

**Comment by RounakTadvi** [comment]
Hmm, Interesting  could you share more details @flutteresbolivia

**Comment by flutteresbolivia** [comment]
> Hmm, Interesting could you share more details @flutteresbolivia

@RounakTadvi  In my country BOLIVIA, my telephone lines, we buy internet packages for hours or days, that is, we buy 100MB x 1 dollar.

Which when that time expires or the MB runs out.

I have to skill the mobile network, but I do not have MB to visit the internet, that is, I have the network enabled, but not the internet, but the plugin gives me a list of addresses and that is wrong.

**Comment by AliPunjabi** [comment]
> My phone does not have internet or megabytes of my mobile or telephone network, but nevertheless it returns me that I am connected, I think the **InternetConnectionChecker().hasConnection** method is failing.

I have the same issue

**Comment by rufw91** [comment]
Definitely doesn't work. Im facing the same issue on iOS and Android emulators

**Comment by bahiraei** [comment]
Yes,I have the same issue.
this package is not stable. too buggy! :(

**Comment by bahiraei** [comment]
D/ConnectivityManager(29476): unregisterNetworkCallback; CallingUid : 11016, CallingPid : 29476

**Comment by rafiiAP** [comment]
same issue :(

**Comment by abuzarbasit** [comment]
Facing the same issue. Kindly Fix it if it is possible. It will help alot

**Comment by tony-ditchlabs** [comment]
I'm making some assumptions here, but presumably you can connect to at least one of the `DEFAULT_ADDRESSES` supplied because your internet provider allows it, but does not allow you traffic to the wider internet. Presumably so you can look up the DNS address of your internet provider and access their site even without any data left.

If I'm right, the workarounds would all be based on replacing the default addresses with ones you come up with - not DNS servers, and not internet providers (including internet providers like Facebook in some areas).

**Comment by RounakTadvi** [comment]
@miguelflores1993  It seems like the InternetConnectionChecker().hasConnection method might not be working correctly in your case. Please ensure you are using the latest version of the package. Additionally, verify that the default addresses are reachable from your country.

If the issue persists, consider creating a custom instance of the class with addresses you can successfully reach. Since this issue has been inactive for a while, I’ll be closing it now. If the problem continues, feel free to open a new issue.
